### ISSUE TITLE
GetTokenFromVismaConnect

### ISSUE THREAD

**Issue by jlmdata** [ON-IT/Visma.Net.Swagger#1]
My application is a service application and services is working with Visma Net ERP Service API.

When I call method   

 `public  async Task<string> GetTokenFromVismaConnect(string clientId, string secret, string tenant_id, string scope = "vismanet_erp_service_api:create vismanet_erp_service_api:delete vismanet_erp_service_api:read vismanet_erp_service_api:update")
    {
            return await VismaNet.GetTokenFromVismaConnect(clientId, secret, tenant_id, scope);
           
     }`

with my client_id, client_secret and Customers tenant_id I get nothing i response. 

What I'am doing wrong?

Authorization via Visma Net swagger page  [https://integration.visma.net/API-index/](url)  with same client id, secret and tenant id is working.

**Comment by omelhus** [comment]
Hey,

We need a bit more context here. Can you recreate the issue with a simple Program.cs and paste the code?

"There's an issue for me with this method" is not much to work with.

- Ole

**Comment by jlmdata** [comment]
`internal class Program
    {  
        static void Main()
        {
            var client_id = "isv_12345-1";
            var client_secret = "ZtC1EyfAp0GmFae7AGbey7vBNgSrnjn7Vv3xaYPKzlcDAHeEBu4pXGzraF39rfYY";
            var tenant_id = "e939844c-b2bd-11ed-8b06-0693d8a7c3dd";
            var classToken = new ClassToken();
            var response = classToken.GetTokenFromVismaConnect(client_id, client_secret, tenant_id);


        }
    }

    internal class ClassToken
    {
        public async Task<string> GetTokenFromVismaConnect(string clientId, string secret, string tenant_id, string scope = "vismanet_erp_service_api:create vismanet_erp_service_api:delete vismanet_erp_service_api:read vismanet_erp_service_api:update")
        {
            return await VismaNet.GetTokenFromVismaConnect(clientId, secret, tenant_id, scope);

        }
    }`

**Comment by omelhus** [comment]
Change static void main to static async Task main and remember await on the get token method.

**Comment by jlmdata** [comment]
Works. But you only get tokens in response. Is there method that gets in return both token and refresh token and time token is valid med tanent id?

**Comment by jlmdata** [comment]
everything is solved. thanks for the help. Now have a better overview of how everything works
